// File generated by the FlutterFire CLI (`flutterfire configure`) for the
// "Hochzeit von Mariandi" Firebase project (web + android). If you ever need
// to regenerate this (e.g. new Firebase project, or adding iOS), run
// `flutterfire configure` again from the `wedapp/` directory.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run `flutterfire configure` to generate real options.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxWHhsd-f5UT7NJaXlxUUfWeuaDIIP8Mc',
    appId: '1:1017083127534:web:fc5afccea58bd34608f5ff',
    messagingSenderId: '1017083127534',
    projectId: 'hochzeit-von-mariandi',
    authDomain: 'hochzeit-von-mariandi.firebaseapp.com',
    storageBucket: 'hochzeit-von-mariandi.firebasestorage.app',
    measurementId: 'G-YWWJPBEBMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqQW3CKkCKNRQ07tSV8RzkCAHUHzBAsaU',
    appId: '1:1017083127534:android:1e439dd5f1c63ffe08f5ff',
    messagingSenderId: '1017083127534',
    projectId: 'hochzeit-von-mariandi',
    storageBucket: 'hochzeit-von-mariandi.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.appspot.com',
    iosBundleId: 'REPLACE_ME',
  );
}
